### ISSUE TITLE
onStartCommand with intent ACTION_STOP called after pause playback

### ISSUE THREAD

**Issue by TheLester** [brianwernick/PlaylistCore#29]
In PlayListServiceCore.java After ACTION_PLAY_PAUSE intent handled , few seconds later onStartCommand with ACTION_STOP called - it closes notification and calls onPlaybackStateChanged (from PlaylistListener) with state STOPPED

**Comment by brianwernick** [comment]
Please include the information requested in the template and any other relevant information

**Comment by TheLester** [comment]
- PlaylistCore version: `1.1.1`
- Device OS version: `6.0.1`
- Devide Manufacturer: `LG`
- Device Name: `Nexus 5`

###### Reproduction Steps

 Run demo - start audio playback - seek to the middle - pause - wait few seconds  

###### Expected Result

Audio Activity and notification are present , waiting for resume.

###### Actual Result

Audio activity finishes and notification disappears.

If you debug sample you'll find out that : 
In PlayListServiceCore.java After ACTION_PLAY_PAUSE intent handled , few seconds later onStartCommand with ACTION_STOP called - it closes notification and calls onPlaybackStateChanged (from PlaylistListener) with state STOPPED

**Comment by TheLester** [comment]
Any progress on this?

**Comment by brianwernick** [comment]
I'm unable to reproduce this with the given information; more information and logs are needed

**Comment by TheLester** [comment]
Seems like i can't reproduce it on Nexus 4 with Androird 4.4.4.
Logs of Nexus 5 6.0.1:
<pre>
11-22 10:02:34.130 27819-27829/com.devbrackets.android.exomediademo W/art: Suspending all threads took: 17.520ms
11-22 10:02:34.157 27819-27819/com.devbrackets.android.exomediademo D/MediaControlsHelper: update, controller is null ? false
11-22 10:02:37.026 27819-27819/com.devbrackets.android.exomediademo D/MediaControlsHelper: update, controller is null ? false
11-22 10:02:38.058 27819-27819/com.devbrackets.android.exomediademo D/MediaControlsHelper: update, controller is null ? false
11-22 10:02:42.411 27819-27819/com.devbrackets.android.exomediademo D/PlaylistServiceCore: Service Destroyed
11-22 10:02:42.412 27819-692/com.devbrackets.android.exomediademo W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {e50cea8} sending message to a Handler on a dead thread
                                                                                  java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {e50cea8} sending message to a Handler on a dead thread
                                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                      at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                      at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                                      at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                                      at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:212)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                      at java.lang.Thread.run(Thread.java:818)
</pre>

Video - https://www.youtube.com/watch?v=TemNFu-KgUE

**Comment by brianwernick** [comment]
The logs you produced point to the ExoMedia demo; are you using the most recent source for the demo?

**Comment by TheLester** [comment]
@brianwernick yeah, its demo from ExoMedia, most recent code (HEAD~ d7d45b8).

**Comment by TheLester** [comment]
Turned out i had notification cleaner on my phone installed that cleans notifications automatically
